### ISSUE TITLE
Version of MNIST used to produce the results presented in the paper

### ISSUE THREAD

**Issue by plonerma** [google/brain-tokyo-workshop#27]
Hello,

the implementation "WANN" only contains a downscaled version of the MNIST task (16x16=256 pixels), while the other two ("prettyNEAT" & "prettyNeatWann") do contain the full image task (MNIST 784 / 28x28) as well as the down-scaled version.
The illustrations in the paper (Figure 7; in the paper) and on the supplementary website suggest they were produced on the MNIST 256 task (16x16 pixels). So, I'm curious whether the presented results (Figure 6, left; in the paper) also refer to the down-scaled version or whether they were in fact produced on the full version.

Thanks a lot for sharing your work!

All the best,
Max

**Comment by agaier** [comment]
Hi Max!

We only ever did tests on the downscaled version, and that is all that is
reported in the paper.

best,
adam

**Comment by plonerma** [comment]
Okay, thanks for the fast answer!
